Repository Alex-Au1/CampusBookingWebApp, pull requests merged in 2025-07, with the labels that each got.

#35 Add Github Action CI Testing for the Unit Tester
  .github/workflows/unit-tests.yml
  Tools/DataImporter/importer.ipynb
  Tools/PyUtils/src/PyUtils/database/DBTool.py
  Tools/UnitTester/README.md
  Tools/UnitTester/src/UnitTester/commandBuilder.py
  Tools/UnitTester/src/UnitTester/config.py
  Tools/UnitTester/src/UnitTester/constants/CommandOpts.py
  Tools/UnitTester/src/UnitTester/constants/ConfigKeys.py
  Tools/UnitTester/src/UnitTester/constants/ShortCommandOpts.py
  Tools/UnitTester/src/UnitTester/unitTester.py
Labels: enhancement

#41 Allow unit tester to fail
  Data/Toy Dataset/Booking.csv
  SQL Queries/Trigger Creation/validBooking.sql
  Tools/DataImporter/importer.ipynb
  Tools/UnitTester/src/UnitTester/unitTester.py
  backend/src/Backend/model/BookingService.py
Labels: bug

#42 Remove unnecessary python dependencies
  backend/src/Backend/model/BookingService.py
  poetry.lock
  pyproject.toml
Labels: tech debt

#55 Add production tests for R7 and R8
  .github/workflows/unit-tests.yml
  SQL Queries/Features/R6/tests/Public/test-production.args
  SQL Queries/Features/R6/tests/Public/test-production.out
  SQL Queries/Features/R7/tests/BookSuccess/test-production.args
  SQL Queries/Features/R7/tests/BookSuccess/test-production.out
  SQL Queries/Features/R7/tests/BookingAlreadyPast/test-production.args
  SQL Queries/Features/R7/tests/BookingAlreadyPast/test-production.out
  SQL Queries/Features/R7/tests/InvalidEndTime/test-production.args
  SQL Queries/Features/R7/tests/InvalidEndTime/test-production.out
  SQL Queries/Features/R7/tests/InvalidStartTime/test-production.args
  SQL Queries/Features/R7/tests/InvalidStartTime/test-production.out
  SQL Queries/Features/R7/tests/InvalidTimeRange/test-production.args
  SQL Queries/Features/R7/tests/InvalidTimeRange/test-production.out
  SQL Queries/Features/R7/tests/OverCapacity/test-production.args
  SQL Queries/Features/R7/tests/OverCapacity/test-production.out
  SQL Queries/Features/R7/tests/OverlapTime/test-production.args
  SQL Queries/Features/R7/tests/OverlapTime/test-production.out
  SQL Queries/Features/R7/tests/RoomNotExists/test-production.args
  SQL Queries/Features/R7/tests/RoomNotExists/test-production.out
  SQL Queries/Features/R7/tests/UserNotExists/test-production.args
  SQL Queries/Features/R7/tests/UserNotExists/test-production.out
  SQL Queries/Features/R8/tests/BookingNotExists/test-production.args
  SQL Queries/Features/R8/tests/BookingNotExists/test-production.out
  SQL Queries/Features/R8/tests/UserNotExists/test-production.args
  SQL Queries/Features/R8/tests/UserNotExists/test-production.out
  SQL Queries/Features/R8/tests/cancelSuccess/test-production.args
  SQL Queries/Features/R8/tests/cancelSuccess/test-production.out
Labels: enhancement

#57 Added R9
  SQL Queries/Features/R9/R9.sql
  backend/src/Backend/App.py
  backend/src/Backend/model/BookingService.py
  frontend/src/App.js
  frontend/src/model/BookingService.jsx
  frontend/src/view/pages/bookingHistory/BookingHistory.jsx
  frontend/src/view/pages/home/index.jsx
  frontend/src/view/pages/viewBooking/ViewBooking.jsx
Labels: enhancement

#58 Minor bug fix and documentation
  README.md
  Tools/DataPopulator/src/DataPopulator/data_generators/BuildingGenerator.py
Labels: documentation

#81 Add bar graph for the frequency a room is booked
  Tools/PyUtils/src/PyUtils/DateTimeTool.py
  backend/src/Backend/App.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/model/DashBoardService.jsx
  frontend/src/tools/DateTimeTools.jsx
  frontend/src/tools/VisualTools.jsx
  frontend/src/view/components/histogram/Histogram.jsx
  frontend/src/view/pages/dashboard/Dashboard.jsx
  frontend/src/view/pages/editAccount/EditAccount.jsx
  frontend/src/view/pages/home/index.jsx
  frontend/src/view/pages/manageBuildings/AddRoomModal.jsx
  frontend/src/view/pages/manageBuildings/ManageBuildings.jsx
  frontend/src/view/pages/signup/Signup.jsx
  frontend/src/view/pages/viewBooking/ViewBooking.jsx
  frontend/src/view/themes/DefaultTheme.jsx
Labels: enhancement

#84 Change the commit date for cancellations
  backend/src/Backend/App.py
  backend/src/Backend/model/BookingService.py
  frontend/src/model/BookingService.jsx
Labels: bug

#92 Add user and room index on the Booking table
  SQL Queries/Table Creation/CreateBooking.sql
  Tools/DataImporter/importer.ipynb
Labels: enhancement

#93 Add unit tests for AF2
  SQL Queries/Features/AF2/tests/HasBookings/test-production.args
  SQL Queries/Features/AF2/tests/HasBookings/test-production.out
  SQL Queries/Features/AF2/tests/HasBookings/test-sample.args
  SQL Queries/Features/AF2/tests/HasBookings/test-sample.out
  SQL Queries/Features/AF2/tests/HasBookings/test-toy.args
  SQL Queries/Features/AF2/tests/HasBookings/test-toy.out
  SQL Queries/Features/AF2/tests/InvalidUser/test-production.args
  SQL Queries/Features/AF2/tests/InvalidUser/test-production.out
  SQL Queries/Features/AF2/tests/InvalidUser/test-sample.args
  SQL Queries/Features/AF2/tests/InvalidUser/test-sample.out
  SQL Queries/Features/AF2/tests/InvalidUser/test-toy.args
  SQL Queries/Features/AF2/tests/InvalidUser/test-toy.out
  SQL Queries/Features/AF2/tests/NoBookings/test-production.args
  SQL Queries/Features/AF2/tests/NoBookings/test-production.out
  SQL Queries/Features/AF2/tests/NoBookings/test-sample.args
  SQL Queries/Features/AF2/tests/NoBookings/test-sample.out
  SQL Queries/Features/AF2/tests/NoBookings/test-toy.args
  SQL Queries/Features/AF2/tests/NoBookings/test-toy.out
  SQL Queries/Features/AF2/tests/UserNotExists/test-production.args
  SQL Queries/Features/AF2/tests/UserNotExists/test-production.out
  SQL Queries/Features/AF2/tests/UserNotExists/test-sample.args
  SQL Queries/Features/AF2/tests/UserNotExists/test-sample.out
  SQL Queries/Features/AF2/tests/UserNotExists/test-toy.args
  SQL Queries/Features/AF2/tests/UserNotExists/test-toy.out
  Tools/UnitTester/UnitTests/__init__.py
  Tools/UnitTester/UnitTests/test_AF2.py
  backend/src/Backend/model/DashboardService.py
Labels: enhancement

#94 Automate creation of admin room log view
  SQL Queries/Features/AF4/CreateViewCommand.sql
  Tools/DataImporter/importer.ipynb
  Tools/DataImporter/src/DataImporter/Importer.py
  Tools/PyUtils/src/PyUtils/database/DBBuilder.py
Labels: enhancement

#95 Add unit tests for AF5
  SQL Queries/Features/AF5/tests/AF5a/UserNotExists/test-production.args
  SQL Queries/Features/AF5/tests/AF5a/UserNotExists/test-production.out
  SQL Queries/Features/AF5/tests/AF5a/UserNotExists/test-sample.args
  SQL Queries/Features/AF5/tests/AF5a/UserNotExists/test-sample.out
  SQL Queries/Features/AF5/tests/AF5a/UserNotExists/test-toy.args
  SQL Queries/Features/AF5/tests/AF5a/UserNotExists/test-toy.out
  SQL Queries/Features/AF5/tests/AF5a/UsernameChanged/test-production.args
  SQL Queries/Features/AF5/tests/AF5a/UsernameChanged/test-production.out
  SQL Queries/Features/AF5/tests/AF5a/UsernameChanged/test-sample.args
  SQL Queries/Features/AF5/tests/AF5a/UsernameChanged/test-sample.out
  SQL Queries/Features/AF5/tests/AF5a/UsernameChanged/test-toy.args
  SQL Queries/Features/AF5/tests/AF5a/UsernameChanged/test-toy.out
  SQL Queries/Features/AF5/tests/AF5a/UsernameTaken/test-production.args
  SQL Queries/Features/AF5/tests/AF5a/UsernameTaken/test-production.out
  SQL Queries/Features/AF5/tests/AF5a/UsernameTaken/test-sample.args
  SQL Queries/Features/AF5/tests/AF5a/UsernameTaken/test-sample.out
  SQL Queries/Features/AF5/tests/AF5a/UsernameTaken/test-toy.args
  SQL Queries/Features/AF5/tests/AF5a/UsernameTaken/test-toy.out
  SQL Queries/Features/AF5/tests/AF5b/IncorrectOldPassword/test-production.args
  SQL Queries/Features/AF5/tests/AF5b/IncorrectOldPassword/test-production.out
  SQL Queries/Features/AF5/tests/AF5b/IncorrectOldPassword/test-sample.args
  SQL Queries/Features/AF5/tests/AF5b/IncorrectOldPassword/test-sample.out
  SQL Queries/Features/AF5/tests/AF5b/IncorrectOldPassword/test-toy.args
  SQL Queries/Features/AF5/tests/AF5b/IncorrectOldPassword/test-toy.out
  SQL Queries/Features/AF5/tests/AF5b/PasswordChanged/test-production.args
  SQL Queries/Features/AF5/tests/AF5b/PasswordChanged/test-production.out
  SQL Queries/Features/AF5/tests/AF5b/PasswordChanged/test-sample.args
  SQL Queries/Features/AF5/tests/AF5b/PasswordChanged/test-sample.out
  SQL Queries/Features/AF5/tests/AF5b/PasswordChanged/test-toy.args
  SQL Queries/Features/AF5/tests/AF5b/PasswordChanged/test-toy.out
  SQL Queries/Features/AF5/tests/AF5b/UserNotExists/test-production.args
  SQL Queries/Features/AF5/tests/AF5b/UserNotExists/test-production.out
  SQL Queries/Features/AF5/tests/AF5b/UserNotExists/test-sample.args
  SQL Queries/Features/AF5/tests/AF5b/UserNotExists/test-sample.out
  SQL Queries/Features/AF5/tests/AF5b/UserNotExists/test-toy.args
  SQL Queries/Features/AF5/tests/AF5b/UserNotExists/test-toy.out
  Tools/UnitTester/UnitTests/__init__.py
  Tools/UnitTester/UnitTests/test_AF5.py
Labels: enhancement
